# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SuShare' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SuShare

  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Storage'
  pod 'Kingfisher'
  pod 'SnapKit'

  target 'SuShareTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
